// Register the service worker for being a PWA.
if ('serviceWorker' in navigator) {
  navigator.serviceWorker
    .register('./sw.js')
    .then((reg) => {
      console.log('Successfully registered.');
    })
    .catch((err) => {
      console.log('Error while registering Service Worker.');
    });
}

function get_todos() {
  var todos = [];
  var todos_str = localStorage.getItem('todo'); // data are stringified before saved
  if (todos_str) {
    todos = JSON.parse(todos_str); // convert stringified data back to its original
  }
  return todos;
}

function add() {
  var task = document.getElementById('task').value;

  var todos = get_todos();
  todos.push(task);
  localStorage.setItem('todo', JSON.stringify(todos));

  show();

  return false; // prevent further action generated by the click event
}

function clearDefault(a) {
  if (a.defaultValue == a.value) {
    a.value = '';
  }
}

function remove() {
  var id = this.getAttribute('id'); // id of the li in ul
  var todos = get_todos();
  todos.splice(id, 1);
  localStorage.setItem('todo', JSON.stringify(todos));

  show();

  return false;
}

function show() {
  var todos = get_todos();

  var html = '<ul>';
  for (var i = 0; i < todos.length; i++) {
    html += `<li> ${todos[i]} <button class="remove" id="${i}">Delete</button></li>`;
  }
  html += '</ul>';

  document.getElementById('todos').innerHTML = html;

  var buttons = document.getElementsByClassName('remove');
  for (var i = 0; i < buttons.length; i++) {
    buttons[i].addEventListener('click', remove);
  }
}

document.getElementById('add').addEventListener('click', add);
show();
